# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from remote_python_sdk import schemas  # noqa: F401


class AmountTaxType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

      Whether the amount given accounts for taxes or not.

  `gross` indicates that the amount given is the amount to be paid before taxes
  are subtracted.

  `net` indicates that the amount given is the amount which will be paid to the
  employee after taxes. Remote will gross this up to ensure the taxes are
  included and employee receives the amount requested without further reduction.

    """


    class MetaOapg:
        enum_value_to_name = {
            "gross": "GROSS",
            "net": "NET",
        }
    
    @schemas.classproperty
    def GROSS(cls):
        return cls("gross")
    
    @schemas.classproperty
    def NET(cls):
        return cls("net")
