# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from remote_python_sdk import schemas  # noqa: F401


class CostCalculatorEmploymentParam(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "region_slug",
        }
        
        class properties:
            region_slug = schemas.StrSchema
            title = schemas.StrSchema
            age = schemas.IntSchema
            annual_gross_salary = schemas.IntSchema
            annual_gross_salary_in_employer_currency = schemas.IntSchema
        
            @staticmethod
            def employment_term() -> typing.Type['EmploymentTermType']:
                return EmploymentTermType
            regional_to_employer_exchange_rate = schemas.StrSchema
            __annotations__ = {
                "region_slug": region_slug,
                "title": title,
                "age": age,
                "annual_gross_salary": annual_gross_salary,
                "annual_gross_salary_in_employer_currency": annual_gross_salary_in_employer_currency,
                "employment_term": employment_term,
                "regional_to_employer_exchange_rate": regional_to_employer_exchange_rate,
            }
    
    region_slug: MetaOapg.properties.region_slug
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region_slug"]) -> MetaOapg.properties.region_slug: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["title"]) -> MetaOapg.properties.title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["age"]) -> MetaOapg.properties.age: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["annual_gross_salary"]) -> MetaOapg.properties.annual_gross_salary: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["annual_gross_salary_in_employer_currency"]) -> MetaOapg.properties.annual_gross_salary_in_employer_currency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employment_term"]) -> 'EmploymentTermType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["regional_to_employer_exchange_rate"]) -> MetaOapg.properties.regional_to_employer_exchange_rate: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["region_slug", "title", "age", "annual_gross_salary", "annual_gross_salary_in_employer_currency", "employment_term", "regional_to_employer_exchange_rate", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region_slug"]) -> MetaOapg.properties.region_slug: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["title"]) -> typing.Union[MetaOapg.properties.title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["age"]) -> typing.Union[MetaOapg.properties.age, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["annual_gross_salary"]) -> typing.Union[MetaOapg.properties.annual_gross_salary, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["annual_gross_salary_in_employer_currency"]) -> typing.Union[MetaOapg.properties.annual_gross_salary_in_employer_currency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employment_term"]) -> typing.Union['EmploymentTermType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["regional_to_employer_exchange_rate"]) -> typing.Union[MetaOapg.properties.regional_to_employer_exchange_rate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["region_slug", "title", "age", "annual_gross_salary", "annual_gross_salary_in_employer_currency", "employment_term", "regional_to_employer_exchange_rate", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        region_slug: typing.Union[MetaOapg.properties.region_slug, str, ],
        title: typing.Union[MetaOapg.properties.title, str, schemas.Unset] = schemas.unset,
        age: typing.Union[MetaOapg.properties.age, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        annual_gross_salary: typing.Union[MetaOapg.properties.annual_gross_salary, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        annual_gross_salary_in_employer_currency: typing.Union[MetaOapg.properties.annual_gross_salary_in_employer_currency, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        employment_term: typing.Union['EmploymentTermType', schemas.Unset] = schemas.unset,
        regional_to_employer_exchange_rate: typing.Union[MetaOapg.properties.regional_to_employer_exchange_rate, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CostCalculatorEmploymentParam':
        return super().__new__(
            cls,
            *args,
            region_slug=region_slug,
            title=title,
            age=age,
            annual_gross_salary=annual_gross_salary,
            annual_gross_salary_in_employer_currency=annual_gross_salary_in_employer_currency,
            employment_term=employment_term,
            regional_to_employer_exchange_rate=regional_to_employer_exchange_rate,
            _configuration=_configuration,
            **kwargs,
        )

from remote_python_sdk.model.employment_term_type import EmploymentTermType
