# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from remote_python_sdk import schemas  # noqa: F401


class EmploymentFullParams(
    schemas.ComposedBase,
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Description of the basic required and onboarding tasks params to create an employment.
You do not need to include all onboarding tasks when creating or updating an employment.

    """


    class MetaOapg:
        required = {
            "country_code",
            "full_name",
            "job_title",
            "personal_email",
        }
        
        class properties:
            country_code = schemas.StrSchema
            full_name = schemas.StrSchema
            job_title = schemas.StrSchema
            personal_email = schemas.StrSchema
            address_details = schemas.DictSchema
            administrative_details = schemas.DictSchema
            bank_account_details = schemas.DictSchema
        
            @staticmethod
            def basic_information() -> typing.Type['EmploymentFullParamsBasicInformation']:
                return EmploymentFullParamsBasicInformation
            billing_address_details = schemas.DictSchema
            company_id = schemas.StrSchema
            contract_details = schemas.DictSchema
            department_id = schemas.StrSchema
            emergency_contact_details = schemas.DictSchema
            manager = schemas.StrSchema
            personal_details = schemas.DictSchema
        
            @staticmethod
            def pricing_plan_details() -> typing.Type['EmploymentFullParamsPricingPlanDetails']:
                return EmploymentFullParamsPricingPlanDetails
            provisional_start_date = schemas.StrSchema
            __annotations__ = {
                "country_code": country_code,
                "full_name": full_name,
                "job_title": job_title,
                "personal_email": personal_email,
                "address_details": address_details,
                "administrative_details": administrative_details,
                "bank_account_details": bank_account_details,
                "basic_information": basic_information,
                "billing_address_details": billing_address_details,
                "company_id": company_id,
                "contract_details": contract_details,
                "department_id": department_id,
                "emergency_contact_details": emergency_contact_details,
                "manager": manager,
                "personal_details": personal_details,
                "pricing_plan_details": pricing_plan_details,
                "provisional_start_date": provisional_start_date,
            }
        
        @classmethod
        @functools.lru_cache()
        def one_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                FullParamsDeprecated,
                FullParams,
            ]

    
    country_code: MetaOapg.properties.country_code
    full_name: MetaOapg.properties.full_name
    job_title: MetaOapg.properties.job_title
    personal_email: MetaOapg.properties.personal_email
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["country_code"]) -> MetaOapg.properties.country_code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["full_name"]) -> MetaOapg.properties.full_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["job_title"]) -> MetaOapg.properties.job_title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personal_email"]) -> MetaOapg.properties.personal_email: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address_details"]) -> MetaOapg.properties.address_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["administrative_details"]) -> MetaOapg.properties.administrative_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bank_account_details"]) -> MetaOapg.properties.bank_account_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["basic_information"]) -> 'EmploymentFullParamsBasicInformation': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billing_address_details"]) -> MetaOapg.properties.billing_address_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["company_id"]) -> MetaOapg.properties.company_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contract_details"]) -> MetaOapg.properties.contract_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["department_id"]) -> MetaOapg.properties.department_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["emergency_contact_details"]) -> MetaOapg.properties.emergency_contact_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["manager"]) -> MetaOapg.properties.manager: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personal_details"]) -> MetaOapg.properties.personal_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pricing_plan_details"]) -> 'EmploymentFullParamsPricingPlanDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["provisional_start_date"]) -> MetaOapg.properties.provisional_start_date: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["country_code", "full_name", "job_title", "personal_email", "address_details", "administrative_details", "bank_account_details", "basic_information", "billing_address_details", "company_id", "contract_details", "department_id", "emergency_contact_details", "manager", "personal_details", "pricing_plan_details", "provisional_start_date", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["country_code"]) -> MetaOapg.properties.country_code: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["full_name"]) -> MetaOapg.properties.full_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["job_title"]) -> MetaOapg.properties.job_title: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personal_email"]) -> MetaOapg.properties.personal_email: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address_details"]) -> typing.Union[MetaOapg.properties.address_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["administrative_details"]) -> typing.Union[MetaOapg.properties.administrative_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bank_account_details"]) -> typing.Union[MetaOapg.properties.bank_account_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["basic_information"]) -> typing.Union['EmploymentFullParamsBasicInformation', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billing_address_details"]) -> typing.Union[MetaOapg.properties.billing_address_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["company_id"]) -> typing.Union[MetaOapg.properties.company_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contract_details"]) -> typing.Union[MetaOapg.properties.contract_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["department_id"]) -> typing.Union[MetaOapg.properties.department_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["emergency_contact_details"]) -> typing.Union[MetaOapg.properties.emergency_contact_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["manager"]) -> typing.Union[MetaOapg.properties.manager, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personal_details"]) -> typing.Union[MetaOapg.properties.personal_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pricing_plan_details"]) -> typing.Union['EmploymentFullParamsPricingPlanDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["provisional_start_date"]) -> typing.Union[MetaOapg.properties.provisional_start_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["country_code", "full_name", "job_title", "personal_email", "address_details", "administrative_details", "bank_account_details", "basic_information", "billing_address_details", "company_id", "contract_details", "department_id", "emergency_contact_details", "manager", "personal_details", "pricing_plan_details", "provisional_start_date", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        country_code: typing.Union[MetaOapg.properties.country_code, str, ],
        full_name: typing.Union[MetaOapg.properties.full_name, str, ],
        job_title: typing.Union[MetaOapg.properties.job_title, str, ],
        personal_email: typing.Union[MetaOapg.properties.personal_email, str, ],
        address_details: typing.Union[MetaOapg.properties.address_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        administrative_details: typing.Union[MetaOapg.properties.administrative_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        bank_account_details: typing.Union[MetaOapg.properties.bank_account_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        basic_information: typing.Union['EmploymentFullParamsBasicInformation', schemas.Unset] = schemas.unset,
        billing_address_details: typing.Union[MetaOapg.properties.billing_address_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        company_id: typing.Union[MetaOapg.properties.company_id, str, schemas.Unset] = schemas.unset,
        contract_details: typing.Union[MetaOapg.properties.contract_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        department_id: typing.Union[MetaOapg.properties.department_id, str, schemas.Unset] = schemas.unset,
        emergency_contact_details: typing.Union[MetaOapg.properties.emergency_contact_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        manager: typing.Union[MetaOapg.properties.manager, str, schemas.Unset] = schemas.unset,
        personal_details: typing.Union[MetaOapg.properties.personal_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        pricing_plan_details: typing.Union['EmploymentFullParamsPricingPlanDetails', schemas.Unset] = schemas.unset,
        provisional_start_date: typing.Union[MetaOapg.properties.provisional_start_date, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'EmploymentFullParams':
        return super().__new__(
            cls,
            *args,
            country_code=country_code,
            full_name=full_name,
            job_title=job_title,
            personal_email=personal_email,
            address_details=address_details,
            administrative_details=administrative_details,
            bank_account_details=bank_account_details,
            basic_information=basic_information,
            billing_address_details=billing_address_details,
            company_id=company_id,
            contract_details=contract_details,
            department_id=department_id,
            emergency_contact_details=emergency_contact_details,
            manager=manager,
            personal_details=personal_details,
            pricing_plan_details=pricing_plan_details,
            provisional_start_date=provisional_start_date,
            _configuration=_configuration,
            **kwargs,
        )

from remote_python_sdk.model.employment_full_params_basic_information import EmploymentFullParamsBasicInformation
from remote_python_sdk.model.employment_full_params_pricing_plan_details import EmploymentFullParamsPricingPlanDetails
from remote_python_sdk.model.full_params import FullParams
from remote_python_sdk.model.full_params_deprecated import FullParamsDeprecated
