# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from remote_python_sdk import schemas  # noqa: F401


class FullParams(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            address_details = schemas.DictSchema
            administrative_details = schemas.DictSchema
            bank_account_details = schemas.DictSchema
            basic_information = schemas.DictSchema
            billing_address_details = schemas.DictSchema
            company_id = schemas.StrSchema
            contract_details = schemas.DictSchema
        
            @staticmethod
            def country() -> typing.Type['Country']:
                return Country
            department_id = schemas.StrSchema
            emergency_contact_details = schemas.DictSchema
            full_name = schemas.StrSchema
            job_title = schemas.StrSchema
            manager_id = schemas.StrSchema
            personal_details = schemas.DictSchema
        
            @staticmethod
            def pricing_plan_details() -> typing.Type['PricingPlanDetails']:
                return PricingPlanDetails
            __annotations__ = {
                "address_details": address_details,
                "administrative_details": administrative_details,
                "bank_account_details": bank_account_details,
                "basic_information": basic_information,
                "billing_address_details": billing_address_details,
                "company_id": company_id,
                "contract_details": contract_details,
                "country": country,
                "department_id": department_id,
                "emergency_contact_details": emergency_contact_details,
                "full_name": full_name,
                "job_title": job_title,
                "manager_id": manager_id,
                "personal_details": personal_details,
                "pricing_plan_details": pricing_plan_details,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address_details"]) -> MetaOapg.properties.address_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["administrative_details"]) -> MetaOapg.properties.administrative_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bank_account_details"]) -> MetaOapg.properties.bank_account_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["basic_information"]) -> MetaOapg.properties.basic_information: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billing_address_details"]) -> MetaOapg.properties.billing_address_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["company_id"]) -> MetaOapg.properties.company_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contract_details"]) -> MetaOapg.properties.contract_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["country"]) -> 'Country': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["department_id"]) -> MetaOapg.properties.department_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["emergency_contact_details"]) -> MetaOapg.properties.emergency_contact_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["full_name"]) -> MetaOapg.properties.full_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["job_title"]) -> MetaOapg.properties.job_title: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["manager_id"]) -> MetaOapg.properties.manager_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["personal_details"]) -> MetaOapg.properties.personal_details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pricing_plan_details"]) -> 'PricingPlanDetails': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["address_details", "administrative_details", "bank_account_details", "basic_information", "billing_address_details", "company_id", "contract_details", "country", "department_id", "emergency_contact_details", "full_name", "job_title", "manager_id", "personal_details", "pricing_plan_details", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address_details"]) -> typing.Union[MetaOapg.properties.address_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["administrative_details"]) -> typing.Union[MetaOapg.properties.administrative_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bank_account_details"]) -> typing.Union[MetaOapg.properties.bank_account_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["basic_information"]) -> typing.Union[MetaOapg.properties.basic_information, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billing_address_details"]) -> typing.Union[MetaOapg.properties.billing_address_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["company_id"]) -> typing.Union[MetaOapg.properties.company_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contract_details"]) -> typing.Union[MetaOapg.properties.contract_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["country"]) -> typing.Union['Country', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["department_id"]) -> typing.Union[MetaOapg.properties.department_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["emergency_contact_details"]) -> typing.Union[MetaOapg.properties.emergency_contact_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["full_name"]) -> typing.Union[MetaOapg.properties.full_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["job_title"]) -> typing.Union[MetaOapg.properties.job_title, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["manager_id"]) -> typing.Union[MetaOapg.properties.manager_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["personal_details"]) -> typing.Union[MetaOapg.properties.personal_details, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pricing_plan_details"]) -> typing.Union['PricingPlanDetails', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["address_details", "administrative_details", "bank_account_details", "basic_information", "billing_address_details", "company_id", "contract_details", "country", "department_id", "emergency_contact_details", "full_name", "job_title", "manager_id", "personal_details", "pricing_plan_details", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        address_details: typing.Union[MetaOapg.properties.address_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        administrative_details: typing.Union[MetaOapg.properties.administrative_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        bank_account_details: typing.Union[MetaOapg.properties.bank_account_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        basic_information: typing.Union[MetaOapg.properties.basic_information, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        billing_address_details: typing.Union[MetaOapg.properties.billing_address_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        company_id: typing.Union[MetaOapg.properties.company_id, str, schemas.Unset] = schemas.unset,
        contract_details: typing.Union[MetaOapg.properties.contract_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        country: typing.Union['Country', schemas.Unset] = schemas.unset,
        department_id: typing.Union[MetaOapg.properties.department_id, str, schemas.Unset] = schemas.unset,
        emergency_contact_details: typing.Union[MetaOapg.properties.emergency_contact_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        full_name: typing.Union[MetaOapg.properties.full_name, str, schemas.Unset] = schemas.unset,
        job_title: typing.Union[MetaOapg.properties.job_title, str, schemas.Unset] = schemas.unset,
        manager_id: typing.Union[MetaOapg.properties.manager_id, str, schemas.Unset] = schemas.unset,
        personal_details: typing.Union[MetaOapg.properties.personal_details, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        pricing_plan_details: typing.Union['PricingPlanDetails', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FullParams':
        return super().__new__(
            cls,
            *args,
            address_details=address_details,
            administrative_details=administrative_details,
            bank_account_details=bank_account_details,
            basic_information=basic_information,
            billing_address_details=billing_address_details,
            company_id=company_id,
            contract_details=contract_details,
            country=country,
            department_id=department_id,
            emergency_contact_details=emergency_contact_details,
            full_name=full_name,
            job_title=job_title,
            manager_id=manager_id,
            personal_details=personal_details,
            pricing_plan_details=pricing_plan_details,
            _configuration=_configuration,
            **kwargs,
        )

from remote_python_sdk.model.country import Country
from remote_python_sdk.model.pricing_plan_details import PricingPlanDetails
