# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from remote_python_sdk.type.currency_definition import CurrencyDefinition
from remote_python_sdk.type.expense_reviewer import ExpenseReviewer
from remote_python_sdk.type.file import File

class RequiredExpense(TypedDict):
    title: str

    amount: int

    converted_amount: int

    converted_currency: CurrencyDefinition

    converted_tax_amount: int

    currency: CurrencyDefinition

    employment_id: str

    expense_date: date

    id: str

    tax_amount: int

class OptionalExpense(TypedDict, total=False):
    # Categories allowed for an expense
    category: str

    invoice_period: typing.Optional[str]

    notes: typing.Optional[str]

    reason: typing.Optional[str]

    receipts: typing.List[File]

    reviewed_at: typing.Optional[date]

    reviewer: typing.Optional[ExpenseReviewer]

    # Expense status
    status: str

class Expense(RequiredExpense, OptionalExpense):
    pass
