# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from remote_python_sdk.type.timeoff_entitlement_entitled import TimeoffEntitlementEntitled
from remote_python_sdk.type.timeoff_entitlement_remaining import TimeoffEntitlementRemaining
from remote_python_sdk.type.timeoff_entitlement_taken import TimeoffEntitlementTaken

class RequiredTimeoffEntitlement(TypedDict):
    # Indicates whether this entitlement can expire.  When `false`, `expiry_date` will be `nil`. 
    can_expire: bool

    entitled: TimeoffEntitlementEntitled

    # Indicates the date this entitlement expires and is no longer counted towards the total time off entitlement for the employment.  When this entitlement doesn't expire, `expiry_date` will be set to `nil`. Use the `can_expire` parameter to determine whether an entitlement can expire or not. 
    expiry_date: typing.Optional[date]

    name: typing.Optional[str]

    remaining: TimeoffEntitlementRemaining

    taken: TimeoffEntitlementTaken

    # Indicates the type of the time off entitlement.  `annual_paid_timeoff` entitlements are calculated from the employment's contract. All other time off entitlements are granted by the employer or automatically by the country of employment. 
    type: str

class OptionalTimeoffEntitlement(TypedDict, total=False):
    pass

class TimeoffEntitlement(RequiredTimeoffEntitlement, OptionalTimeoffEntitlement):
    pass
