# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from remote_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_CONTRACTAMENDMENTS = "/v1/contract-amendments"
    V1_TIMEOFF_ID = "/v1/timeoff/{id}"
    V1_INCENTIVES = "/v1/incentives"
    V1_CUSTOMFIELDS = "/v1/custom-fields"
    V1_COSTCALCULATOR_ESTIMATIONPDF = "/v1/cost-calculator/estimation-pdf"
    V1_INCENTIVES_ID = "/v1/incentives/{id}"
    V1_PAYSLIPS = "/v1/payslips"
    AUTH_OAUTH2_TOKEN = "/auth/oauth2/token"
    V1_EMPLOYMENTCONTRACTS_EMPLOYMENT_ID_PENDINGCHANGES = "/v1/employment-contracts/{employment_id}/pending-changes"
    V1_TIMEOFF = "/v1/timeoff"
    V1_EMPLOYMENTS_EMPLOYMENT_ID = "/v1/employments/{employment_id}"
    V1_PAYSLIPS_ID = "/v1/payslips/{id}"
    V1_INCENTIVES_RECURRING_ID = "/v1/incentives/recurring/{id}"
    V1_SANDBOX_EMPLOYMENTS_EMPLOYMENT_ID = "/v1/sandbox/employments/{employment_id}"
    V1_RESIGNATIONS_EMPLOYMENT_REQUEST_ID_RESIGNATIONLETTER = "/v1/resignations/{employment_request_id}/resignation-letter"
    V1_EXPENSES = "/v1/expenses"
    V1_COMPANYDEPARTMENTS = "/v1/company-departments"
    V1_EXPENSES_ID = "/v1/expenses/{id}"
    V1_BENEFITS_COUNTRYSUMMARY = "/v1/benefits/country-summary"
    V1_COMPANYMANAGERS = "/v1/company-managers"
    V1_PAYSLIPS_PAYSLIP_ID_PDF = "/v1/payslips/{payslip_id}/pdf"
    V1_IDENTITY_CURRENT = "/v1/identity/current"
    V1_FILES_ID = "/v1/files/{id}"
    V1_OFFBOARDINGS = "/v1/offboardings"
    V1_COMPANYMANAGERS_USER_ID = "/v1/company-managers/{user_id}"
    V1_CUSTOMFIELDS_CUSTOM_FIELD_ID_VALUES_EMPLOYMENT_ID = "/v1/custom-fields/{custom_field_id}/values/{employment_id}"
    V1_CONTRACTAMENDMENTS_ID = "/v1/contract-amendments/{id}"
    V1_COMPANIES = "/v1/companies"
    V1_CONTRACTAMENDMENTS_AUTOMATABLE = "/v1/contract-amendments/automatable"
    V1_SANDBOX_EMPLOYMENTS = "/v1/sandbox/employments"
    V1_CONTRACTAMENDMENTS_SCHEMA = "/v1/contract-amendments/schema"
    V1_BILLINGDOCUMENTS = "/v1/billing-documents"
    V1_INCENTIVES_RECURRING = "/v1/incentives/recurring"
    V1_COUNTRIES = "/v1/countries"
    V1_COSTCALCULATOR_REGIONS_SLUG_FIELDS = "/v1/cost-calculator/regions/{slug}/fields"
    V1_WEBHOOKCALLBACKS_ID = "/v1/webhook-callbacks/{id}"
    V1_COUNTRIES_COUNTRY_CODE_HOLIDAYS_YEAR = "/v1/countries/{country_code}/holidays/{year}"
    V1_BILLINGDOCUMENTS_BILLING_DOCUMENT_ID_PDF = "/v1/billing-documents/{billing_document_id}/pdf"
    V1_DOCUMENTS = "/v1/documents"
    V1_WEBHOOKCALLBACKS = "/v1/webhook-callbacks"
    V1_COSTCALCULATOR_ESTIMATION = "/v1/cost-calculator/estimation"
    V1_EXPENSES_EXPENSE_ID_RECEIPT = "/v1/expenses/{expense_id}/receipt"
    V1_EMPLOYMENTS_EMPLOYMENT_ID_INVITE = "/v1/employments/{employment_id}/invite"
    V1_TIMEOFFBALANCES_EMPLOYMENT_ID = "/v1/timeoff-balances/{employment_id}"
    V1_BILLINGDOCUMENTS_BILLING_DOCUMENT_ID = "/v1/billing-documents/{billing_document_id}"
    V1_EXPENSES_EXPENSE_ID_RECEIPTS_RECEIPT_ID = "/v1/expenses/{expense_id}/receipts/{receipt_id}"
    V1_EMPLOYMENTS = "/v1/employments"
    V1_COSTCALCULATOR_COUNTRIES = "/v1/cost-calculator/countries"
    V1_OFFBOARDINGS_ID = "/v1/offboardings/{id}"
    V1_SANDBOX_WEBHOOKCALLBACKS_TRIGGER = "/v1/sandbox/webhook-callbacks/trigger"
    V1_TIMEOFF_TYPES = "/v1/timeoff/types"
    V1_COMPANIES_COMPANY_ID = "/v1/companies/{company_id}"
    V1_READY = "/v1/ready"
    V1_SANDBOX_CONTRACTAMENDMENTS_CONTRACT_AMENDMENT_REQUEST_ID_APPROVE = "/v1/sandbox/contract-amendments/{contract_amendment_request_id}/approve"
    V1_COUNTRIES_COUNTRY_CODE_FORM = "/v1/countries/{country_code}/{form}"
