# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from remote_python_sdk.paths.v1_countries_country_code_form.get import GetFormSchema
from remote_python_sdk.paths.v1_countries.get import ListAlphabetically
from remote_python_sdk.paths.v1_countries_country_code_holidays_year.get import ListHolidaysByYear
from remote_python_sdk.apis.tags.countries_api_raw import CountriesApiRaw


class CountriesApi(
    GetFormSchema,
    ListAlphabetically,
    ListHolidaysByYear,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CountriesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CountriesApiRaw(api_client)
