# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from remote_python_sdk.paths.v1_ready.post import CompleteOnboardingRaw
from remote_python_sdk.paths.v1_employments.post import CreateEmploymentRaw
from remote_python_sdk.paths.v1_employments_employment_id.get import GetEmploymentInfoRaw
from remote_python_sdk.paths.v1_employments_employment_id_invite.post import InviteStartEnrollmentRaw
from remote_python_sdk.paths.v1_employments.get import ListAllRaw
from remote_python_sdk.paths.v1_employments_employment_id.patch import UpdateDataRaw
from remote_python_sdk.paths.v1_employments_employment_id.put import UpdateDetailsRaw


class EmploymentsApiRaw(
    CompleteOnboardingRaw,
    CreateEmploymentRaw,
    GetEmploymentInfoRaw,
    InviteStartEnrollmentRaw,
    ListAllRaw,
    UpdateDataRaw,
    UpdateDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
