# coding: utf-8

"""
    Remote API

    Talent is everywhere. Opportunity is not. Remote's mission is to create opportunity everywhere, empowering employers to find and hire the best talent, and enabling individuals to build financial and personal freedom.   Remote is a Global HR Platform that helps companies hire, manage, and pay their entire team — and more effectively compete in the modern global economy through our comprehensive set of core solutions including, HRIS, payroll, international employment, contractor management, and more.   Whether you're just starting your global journey, or looking to optimize your existing operations, sign up or book a demo - and see how Remote makes global HR simple.

    The version of the OpenAPI document: 0.1.0
    Generated by: https://konfigthis.com
"""

from remote_python_sdk.paths.v1_offboardings.post import CreateRequest
from remote_python_sdk.paths.v1_offboardings.get import ListRequests
from remote_python_sdk.paths.v1_offboardings_id.get import ShowRequest
from remote_python_sdk.apis.tags.offboarding_api_raw import OffboardingApiRaw


class OffboardingApi(
    CreateRequest,
    ListRequests,
    ShowRequest,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OffboardingApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OffboardingApiRaw(api_client)
